name: .NET Build, Test & Pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/EtaEstimator/EtaEstimator.csproj

    - name: Build
      run: dotnet build src/EtaEstimator/EtaEstimator.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test EtaEstimator.sln --configuration Release --no-build --verbosity normal

    - name: Pack NuGet
      run: dotnet pack src/EtaEstimator/EtaEstimator.csproj --configuration Release -o ./artifacts

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: EtaEstimator-nuget
        path: ./artifacts/*.nupkg
