name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore EtaEstimator/src/EtaEstimator/EtaEstimator.csproj

    - name: Build
      run: dotnet build EtaEstimator/src/EtaEstimator/EtaEstimator.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test EtaEstimator/src/EtaEstimator.sln --configuration Release --no-build --verbosity normal
